name: cd

on:
  pull_request:
    branches:
      - master
    types:
      - closed

env:
  DOCKERHUB_USERNAME: switzerchees
  KUBERNETES_NAMESPACE: my-garden
  APP_NAME: my-garden
  BASE_URL: m324ab05kyh.hackerman.ch
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: keith
    steps:
      # - name: Get current date
      #   id: date
      #   uses: Kaven-Universe/github-action-current-date-time@v1
      #   with:
      #     format: 'YYYY_MM_DD_HH_mm_ss'

      # - run: echo "${{ steps.date.outputs.time }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER_KEITH }}
          password: ${{ secrets.DOCKERHUB_PW_KEITH }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USER_KEITH }}/simple_ts:latest

      - name: Check and Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
        id: install

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Replace and Apply Kubernetes Manifests
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            .k8s/namespace.yml
            .k8s/deployment.yml
            .k8s/service.yml
            .k8s/ingress.yml
          replacement-method: defined
