name: cd

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  deploy:
    runs-on: keith
    steps:
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: 'YYYY_MM_DD_HH_mm_ss'

      - run: echo "${{ steps.date.outputs.time }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER_KEITH }}
          password: ${{ secrets.DOCKERHUB_PW_KEITH }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USER_KEITH }}/simple_ts:${{ steps.date.outputs.time }}
