name: Lint Test Build
run-name: ${{ github.actor }} is running continuous integration🚀
on: [push]
jobs:
  Basic-Integration:
    runs-on: ubuntu-runners
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build
