name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  integrate:
    runs-on: keith
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
