name: Lint Test Build
run-name: ${{ github.actor }} is running continuous🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-runners
    steps:
      - run: npm i
      - run: npm run lint
      - run: npm test
      - run: npm build
